### ISSUE TITLE
Download bar in fullscreen mode

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#132]
When playing a fullscreen video in youtube, it keeps showing the download bar on the bottom. Ideally it should hide as well.

**Comment by alcinnz** [comment]
Oh, I never noticed that. Should be a trivial fix.

**Comment by alcinnz** [comment]
Committed a fix and will be release an upgrade today. Hopefully this one makes it out to you guys, it's sounding promising now.
