### ISSUE TITLE
Scrollbars Not Rendered Correctly

### ISSUE THREAD

**Issue by alcinnz** [alcinnz/Odysseus#14]

**Comment by giovannicaligaris** [comment]
![screencast from 2018-01-05 15 26 38](https://user-images.githubusercontent.com/26255347/34615683-abc97606-f22d-11e7-918e-0e7ef2583ab5.gif)

**Comment by giovannicaligaris** [comment]
The only way to solve this in Epiphany is by adding a user-styleshee.css file in ~/.config/epiphany

```
html::-webkit-scrollbar {
    width: 7px;
    height: 7px;
    background: #fff;
    border-radius: 3ex;
}

html::-webkit-scrollbar:hover {
    background: #e6e6e6;
}

html::-webkit-scrollbar-track {
    display: none;
}

html::-webkit-scrollbar-track-piece,
html::-webkit-scrollbar-button {
    display: none;
}

html::-webkit-scrollbar-thumb {
    background: #848484;
    border-radius: 3ex;
    border: 2px solid #fff;
}

html::-webkit-scrollbar-thumb:hover {
    background: #7a7a7a;
    border: none;
}
```

And enabling custom user-styleshee from Dconf

**Comment by alcinnz** [comment]
Thank you for the CSS. I tried writing some myself, but I guess I was too much of a perfectionist to finish. 

The root problem however lies in WebKitGTK and an architectural decision made by core WebKit. You see all the scrollbars, text entries, checkboxes, etc (that is everything except the popup menus) are not the actual controls provided by GTK but rather emulations of them (which may share some but not all rendering code). WebKit's however been handling things very well given this decision, but the scrollbar rendering code has diverged between it and GTK. That makes a user visible difference.

The good news is that Apple is doing something similar, but not quite as nice, in their ports of WebKit; so fixing this upstream (where me, Epiphany, and all apps with embedded web rendering will benefit) shouldn't be too hard. However I don't know how long that'll take or even if it'll make it in Loki, so in the meantime I'll apply you're CSS.

**Comment by alcinnz** [comment]
Hmmm, works in the browser preview of scratch but not when I tried applying it as a userstylesheet in Odysseus it didn't.

P.S. So far I've been hardcoding the userstylesheets into Odysseus. I'm however keen to allow installing of userscripts off the Web eventually.

**Comment by alcinnz** [comment]
Tried again and I don't understand why I can't seem to apply these styles. I believe I've toggled all the settings, but it's only working as an inline style (which is not tested within Odysseus) rather than a user style.

I'm not happy about it, but I think I'll move on to other issues.

**Comment by giovannicaligaris** [comment]
Any progress on this?

**Comment by alcinnz** [comment]
I'm really perplexed by why what I've done isn't working.

I'm not really sure where to go from here, but I'll include this issue on a new priority list and revisit it soon.

**Comment by alcinnz** [comment]
Also I have been studying WebKit to figure out how to fix the problem at the core. So that's been my focus.

**Comment by alcinnz** [comment]
Fixed upstream on [April 12th 2016](https://trac.webkit.org/changeset/199344/webkit/trunk/Source/WebCore/platform/gtk/ScrollbarThemeGtk.cpp).

I don't know when Debian will release these fixes, but all we need to do is what. So I'm closing this issue.
