### ISSUE TITLE
Improper icons on GNOME/Adwaita

### ISSUE THREAD

**Issue by bugaevc** [alcinnz/Odysseus#141]
GNOME apps use `Gtk.IconSize.BUTTON` for the icons of the headerbar buttons. Odysseus — like other Elementary apps I've seen — is using `Gtk.IconSize.LARGE_TOOLBAR`, which makes its icons look oversized on GNOME:

![image](https://user-images.githubusercontent.com/10091584/46016359-3c7e0f80-c0dd-11e8-8975-5a718252d81e.png)

Here's what it looks like after fixing the size:

![image](https://user-images.githubusercontent.com/10091584/46017892-40139580-c0e1-11e8-8845-310960ab1221.png)

You'd probably want to keep using `LARGE_TOOLBAR` on Elementary though.

Other headerbar/icons issues:
* Back/forward buttons should be "linked". I'm not sure how to achieve this using `HeaderBarWithMenus`/`ButtonWithMenu`, but GNOME apps like Web do it by putting the buttons into a `Gtk.Box` that has a `.linked` style class.
* Odysseus uses an Elementary-style symbolic icon named `open-menu` ([shipped with libgranite](https://github.com/elementary/granite/blob/master/icons/48x48/open-menu.svg)); GNOME apps use `open-menu-symbolic` instead (on Adwaita, it looks like a hamburger icon).

**Comment by alcinnz** [comment]
I can put whatever I want in that header bar, and the reload/cancel is actually a `Gtk.Stack`. So I think it'll be trivial to add that `.linked` box, and should make no difference on elementary.

And similarly elementary provides a symbolic version of `open-menu`. So maybe it'd be better for the entire header bar to be symbolic anyways...

As for the central issue: hmmm, what should the condition be to decide the icon size?

**Comment by bugaevc** [comment]
> As for the central issue: hmmm, what should the condition be to decide the icon size?

I'm not sure... Do you want Odysseus to look "like GNOME" or "like Elementary" when run on e.g. KDE? Do you want it to look like Elementary when run in GNONE with the Elementary GTK theme selected?

**Comment by alcinnz** [comment]
To transform this issue into a checklist:

- [ ] Fix toolbar icon sizes on non-elementary desktops. I'll default to smaller icons because that's probably less likely to cause issues.
- [ ] Switch to open-menu-symbolic for application menu.
- [ ] link backwards/forwards buttons.

**Comment by alcinnz** [comment]
I've solved the core issue, and I think I'll open another one for what remains on that checklist.
