### ISSUE TITLE
Mispositioned menu on Wayland

### ISSUE THREAD

**Issue by bugaevc** [alcinnz/Odysseus#142]
See the screenshot:

![image](https://user-images.githubusercontent.com/10091584/46018819-6b977f80-c0e3-11e8-8bb5-53268b87476e.png)

When running Odysseus using the X11 GTK backend the menu is positioned properly.

Obviously, this is happening because Odysseus tries to implement its own menu positioning logic — `ButtonWithMenu.get_menu_position ()` — using global coordinates, which of course doesn't work on Wayland as there are no global coordinates. The correct way of doing this is leaving menu positioning up to GTK, which uses `xdg_positioner` on Wayland and some similar half-broken global coordinates shenanigans on X11. In particular, use `GtkMenu.popup_at_widget ()`.

Misc notes:
* Menu icons are missing, probably something Elementary-specific...
* It's better to use popups over old-style menus anyway

**Comment by alcinnz** [comment]
On the mispositioning: I actually copied that code from Pantheon Files. I think I'll check if it needs fixing there too.

On the icons: I wasn't sure if they were a good idea or not, but to indicate they're essentially links. Now I've just realized I can communicate more with them to bring off the fence!

Also that's where the broken icons are! I put some to work into limiting myself to the standard set (plus `open-menu`.

As for popovers: I don't find I have much need of them yet. But given a reason to switch I will.

**Comment by alcinnz** [comment]
Committing a fix to the core issue now, and yesterday I fixed the problem with the icons. I decided just to get rid of them, I really wasn't sure whether or not they were a good idea so this pushed me out of my uncertainty.

**Comment by alcinnz** [comment]
Also I'm now seeing a weird issue with the menu seperators not showing up in the application menu despite them showing up when switching via GTK inspector and in other menus in my app.

I'll try switching to popovers to see if that'll make the menu well-organized again.

**Comment by alcinnz** [comment]
Ugh, too much legacy code to work through in order to try using a PopoverMenu (I copied it from elsewhere and will contribute a fix there).

But apart from that minor consistancy problem (which will need to be fixed eventually), I'll consider this issue fixed.
