### ISSUE TITLE
Open dialog issues

### ISSUE THREAD

**Issue by bugaevc** [alcinnz/Odysseus#143]
This is what the Open dialog (Menu → Open) looks like:

![image](https://user-images.githubusercontent.com/10091584/46019790-91258880-c0e5-11e8-97be-33d0319a898a.png)

For the reference, here's what it looks like in other apps:

![image](https://user-images.githubusercontent.com/10091584/46020141-596b1080-c0e6-11e8-935d-a2e2c6b5a8e4.png)

Issues:
* It's titled "_Open" instead of "Open" (something related to accelerators is not working?)
* The Open button is not blue, i.e. does not have the `.suggested-action` class
* It doesn't display my pinned folders, mounts, etc. in the sidebar
* Are you even using `Gtk.FileChooserNative`? It seems that you don't, which means:
    * We have to use `--filesystem=host`
    * And even with that, the dialog is actually displaying the fs layout inside Flatpak, if you look closely

**Comment by alcinnz** [comment]
Yes,  I am using `--filesystem=host` in my FlatPak metadata. So that turns off the sand boxing of the filesystem? (Good, I probably need it)

What else might be the issue there? How'd I diagnose it?

**Comment by alcinnz** [comment]
The issue with the title should be a quick fix, it seems I did a rush job on abstracting this.

As for the non-default Open button I'll look into it.

**Comment by bugaevc** [comment]
> Yes, I am using --filesystem=host in my FlatPak metadata. So that turns off the sand boxing of the filesystem? (Good, I probably need it)

Kinda. It mounts (parts of) host's filesystem over `/var/run/host`. I don't know what you have in mind, but most apps don't actually need either that or even `/home`.

> What else might be the issue there? How'd I diagnose it?

... you're not using `Gtk.FileChooserNative`. Do that, and everything will just work (even with no host or home access).

**Comment by alcinnz** [comment]
Those tangential questions have been moved to #144

**Comment by alcinnz** [comment]
I just committed a fix for both the incorrect title and the sandboxing issues (the latter of which I gather also fixes the fact open is not the suggested action).
