### ISSUE TITLE
Build with vala >= 0.42.2

### ISSUE THREAD

**Issue by awissu** [alcinnz/Odysseus#150]
```
[   75s] ../src/BrowserWindow.vala:102.17-102.29: error: Argument 3: Cannot convert from `uint' to `int'
[   75s]                 Gdk.Key.comma, () => web.go_back(), (menu) => {
[   75s]                 ^^^^^^^^^^^^^
[   75s] ../src/BrowserWindow.vala:110.17-110.30: error: Argument 3: Cannot convert from `uint' to `int'
[   75s]                 Gdk.Key.period, () => web.go_forward(), (menu) => {
```
More info: https://build.opensuse.org/public/build/home:awissu:branches:X11:Pantheon:Apps/openSUSE_Tumbleweed/x86_64/odysseus/_log

**Comment by alcinnz** [comment]
I just committed a fix! Newer versions of Vala seem to be a bit more fussy.

Am I right in thinking your packaging Odysseus for OpenSUSE? If so please tell me when it has successfully built, I'd like to link to it.

**Comment by awissu** [comment]
> If so please tell me when it has successfully built, I'd like to link to it.

Fixed.
> Am I right in thinking your packaging Odysseus for OpenSUSE?

https://software.opensuse.org/package/odysseus?search_term=odysseus

**Comment by alcinnz** [comment]
Hmmm. I think I could update my plain text description...

Also do `appstream:` links work on OpenSUSE? Because that'll help simplify my web design, and improve some of Odysseus's error screens.

And Odysseus has some hardcoded recommended links to fill in for a lack of topsites, some of which are elementary OS specific. For OpenSUSE I'd like to replace those with OpenSUSE-specific links. Any recommendations?

**Comment by awissu** [comment]
> Also do appstream: links work on OpenSUSE?

https://github.com/openSUSE/software-o-o/pull/358

> And Odysseus has some hardcoded recommended links to fill in for a lack of topsites, some of which are elementary OS specific. For OpenSUSE I'd like to replace those with OpenSUSE-specific links

Example?

**Comment by alcinnz** [comment]
On AppStream, cool! Doesn't look too far away.

As for the recommended links I've got them all at https://github.com/alcinnz/Odysseus-recommendations/tree/master/links , with a visual rendering at http://recommendations.adrian.geek.nz/ . I've started extracting the elementary-specific links into https://github.com/alcinnz/Odysseus-recommendations/tree/master/links/elementary.tsv , so take a look at that.

**Comment by awissu** [comment]
Ok.
Here are the recommended links for openSUSE:
https://build.opensuse.org/package/view_file/network/palemoon/distribution.ini.in?expand=1
