### ISSUE TITLE
Mint OS : Address bar and its icons are wide except when opening a new tab 

### ISSUE THREAD

**Issue by gkrishnaks** [alcinnz/Odysseus#158]
Hi,
My PC details below. I cloned Odysseus today and built from master.

Sharing observation which I earlier pinged to Adrian in Mastodon : 

Attaching picture of how the address bar and icons appear in my Mint GNU/Linux box - incorrect width
![Screenshot](https://user-images.githubusercontent.com/6957430/55421917-13f93580-5598-11e9-96c6-4cba2e32c559.png)

But when I open a new tab, i.e the open new tab Action, for few moments it resizes to expected icon/address bar size like in below pic. Once the tab's thumbnails appear, the icons and address becomes wide again. 
![Screenshot from 2019-04-02 22-33-49](https://user-images.githubusercontent.com/6957430/55422370-1f009580-5599-11e9-9d2d-2164e0445a6d.png)

System details :
```
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara

uname -a
Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alcinnz** [comment]
Ooooh weird, doesn't look like my first thought. My next theory is that that the addressbar status icons (which shows in the section to the right of the addressbar) are too large. Also I'm noticing that I'm not seeing an icon that should appear there for the homepage.

**Comment by alcinnz** [comment]
I've got the sizing issue at least fixed, and testing on GNOME3 the icons seem to be fine. And it even seems to make a (less noticable) positive difference on elementary.

Please reopen if this is still on issue.
