### ISSUE TITLE
FR: Need switch to globally disallow JS

### ISSUE THREAD

**Issue by gkrishnaks** [alcinnz/Odysseus#159]
Hi,
I tried to search for a switch to just globally disallow JS. Please consider this a feature request :)
Thanks.

**Comment by alcinnz** [comment]
Looking at the APIs I have access to, this needs to be a startup action. Though maybe I can do better by implementing this as a "Content Blocker" when I add support for those.

I must say my ideal would be to just not support it in Odysseus, but I don't think we can do so. Too many sites rely on JavaScript.

**Comment by alcinnz** [comment]
Yup, this can be done using a Content Blocker something like:

    {'trigger': {'url-filter': '.*', 'resource-type': ['script']}, 'action': {'type': 'block'}}

This would allow you to turn it on and off as you please, and even make exceptions.

That said I'd need to see if I have access to that API yet (it only got committed recently), and I'm planning on managing the set of installed Content Blockers through a bookmarking interface that isn't yet implemented.

**Comment by alcinnz** [comment]
I'm closing this in favor of #162 , which better suits the APIs I have to work with.

Please pitch in some design ideas!
