### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by danrabbit** [alcinnz/Odysseus#161]
Thanks for submitting Odysseus 1.5.14 to AppCenter!

I've marked this release as "needs fixing" because it appears that the UI has changed, but screenshots have not been updated to match. Please update your screenshots and then submit a new release to AppCenter

**Comment by alcinnz** [comment]
Fair enough, I believe you're referring to the new status area of the addressbar.

I'll take the new screenshots tomorrow so I have time to build up a sample browser history database to demonstrate some other UIs I have.
