### ISSUE TITLE
Prompts for setting as default every single time

### ISSUE THREAD

**Issue by cassidyjames** [alcinnz/Odysseus#164]
This really should remember the user dismissed it and not badger them every single time they open the app.

**Comment by alcinnz** [comment]
Good point, totally forgot about that workflow!

Since I'm already detecting first launch in order to show an initial page I think I'll use that condition.

**Comment by alcinnz** [comment]
That was a trivial fix!

Took more effort to fiddle around with my settings to test it properly.

**Comment by alcinnz** [comment]
Also I'm trying to rerelease the update now, but Houston seems to be down.
