### ISSUE TITLE
Please update `pages-l10n` content

### ISSUE THREAD

**Issue by NathanBnm** [alcinnz/Odysseus#168]
Lines number aren't correct anymore, can you update them? I don't really know how to proceed.

Did you think about a better way to do this?

**Comment by alcinnz** [comment]
I'll regenerate the main file with some additional text to translate soon.

But to answer your question, I found Gettext kept crashing when combined with the templating language in which those internal pages are written. So I switched to an alternate format I already had implemented most of the code to parse and was easy for my scripts to write out.

Though ofcourse the drawback is a lack of good tools for localizers.

**Comment by alcinnz** [comment]
As for solutions I was thinking about standing up a custom WebLate instance, though now that I think about it maybe there's a more standard XML format I can use as an intermediary?

**Comment by alcinnz** [comment]
I think I'll probably just develop a few more commandline tools, because now I have something to test against.

**Comment by NathanBnm** [comment]
I'm not very experienced with that, but maybe you can use JSON. It would be easier to read for translators.
The elementary website is working this way, I don't know if it's applicable to your app, maybe you can create the appropriate script. For example with the fr folder: https://github.com/elementary/website/tree/master/_lang/fr

**Comment by alcinnz** [comment]
Those translation files are updated now, and I have some new commandline tools to help manage them. Including one that can guide localizers in writing their translations. Though I might add another to monitor progress.

These were easy to write because now I had files to test against, and because they share a very similar syntax with the programming language being localized.

Please give me feedback on their usefullness! I know the merge is a little finnicky.

**Comment by NathanBnm** [comment]
Okay great :smile: I'll take a look at that (I have to check those translations).

Can you please make some documentation about these scripts? You have to tell translators about how to use them.

**Comment by NathanBnm** [comment]
I opened #171 but I'm not sure if it's good. I have to wait for you to check and make doc as I said just above.

**Comment by alcinnz** [comment]
Your pull request looked great!

Please tell me how useful this documentation is: https://odysseus.adrian.geek.nz/guides/contributing.html#localization .

**Comment by NathanBnm** [comment]
Thanks

Yes that looks clear!
