### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by NathanBnm** [alcinnz/Odysseus#169]
It would be great if there was a dark theme.

**Comment by alcinnz** [comment]
Be reasonable to have this follow along with: https://medium.com/elementaryos/the-need-for-a-freedesktop-dark-style-preference-614f501ae4ca

**Comment by alcinnz** [comment]
I've just implemented support for the future/global "prefer dark mode" preference.

Ordinarily I wouldn't to close an issue before the UI to utilize it is committed, but it looks like elementary will be creating their own soon enough (which I don't want to duplicate) so I'll make an exception here.
