### ISSUE TITLE
NixOS: Webpages do not render.

### ISSUE THREAD

**Issue by alcinnz** [alcinnz/Odysseus#173]
While the pages do appear to be receiving input events and notifying Odysseus of any links being hovered over, nothing is being rendered to screen.

Reported by @clacke .

**Comment by alcinnz** [comment]
Some packages that might be useful to look at:

https://github.com/NixOS/nixpkgs/blob/f70e66cccd5ac6e39f6de595b5f770b35601cf55/pkgs/desktops/gnome-3/core/epiphany/default.nix#L45
https://github.com/NixOS/nixpkgs/blob/f70e66cccd5ac6e39f6de595b5f770b35601cf55/pkgs/applications/networking/browsers/firefox/wrapper.nix

**Comment by alcinnz** [comment]
And this issue looks relevant: https://github.com/NixOS/nixpkgs/issues/32580

**Comment by worldofpeace** [comment]
Hi I maintain Pantheon in NixOS.

We had a similar problem with ephemeral https://github.com/NixOS/nixpkgs/pull/61665#issuecomment-493714457
This was fixed by adding `glib-networking` to `buildInputs`.
It needs `glib-networking` in `GIO_EXTRA_MODULES` to work.
