### ISSUE TITLE
Cannot leave reader mode without reloading

### ISSUE THREAD

**Issue by alexbuzzbee** [alcinnz/Odysseus#176]
There does not appear to be an "exit reader mode" button. It seems like the only way to leave reader mode once entered is to reload the page. Clicking the reader mode button again just shows the themes list.

**Comment by alcinnz** [comment]
That's correct, and even if I added an option to leave Reader Mode to that menu behind the scenes it would still be a reload. And I'd like that to be clear.

Should I add a reload option to that menu as a compromise?

**Comment by alexbuzzbee** [comment]
Even if it's still actually a reload, having an explicit "exit Reader Mode" option would be more intuitive.

**Comment by alcinnz** [comment]
I just committed a fix, and it will be part of the next release.
