### ISSUE TITLE
Enable back/forward gesture in webkit

### ISSUE THREAD

**Issue by Exalm** [alcinnz/Odysseus#178]
WebKit supports a back-forward swipe gesture since 2.24. Epiphany already has it, would be cool for Odysseus to have it too :)

https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--enable-back-forward-navigation-gestures, valadoc is a bit outdated

**Comment by alcinnz** [comment]
O.K., I'll take another look through WebKitSettings. It seems like there's a number of new proporties I should consider enabling.

**Comment by alcinnz** [comment]
Went through and configured all those new settings, with a few judgemental comments. Could've been more judgemental but it got repetitive complaining about (what I consider) bloat that I'm enabling for the sake of compatibility.

Committing them now and this'll make it into the next release.

**Comment by alcinnz** [comment]
Thanks a lot for bringing this to my attention!

It is a very nice gestures!
