### ISSUE TITLE
Typo in latest release "version"

### ISSUE THREAD

**Issue by cassidyjames** [alcinnz/Odysseus#185]
https://github.com/alcinnz/Odysseus/blob/53ac7b56ed21ea42486508dd7ae5d5bb167223cd/data/com.github.alcinnz.odysseus.appdata.xml.in#L57

**Comment by alcinnz** [comment]
Fixed, do you want me to resubmit?

**Comment by cassidyjames** [comment]
@alcinnz 1.6.1 was accepted (and exposed a bug in [appcenter.elementary.io](https://appcenter.elementary.io), heh), but your 1.6.1 release notes won't show up in AppCenter. You could resubmit a new version (i.e. 1.6.2) if you'd like, but it will also resolve itself with your next normal release.

**Comment by alcinnz** [comment]
O.K., I don't think I will resubmit. I don't think it's worth it, the changes were minor.
