### ISSUE TITLE
Shouldn't be possible to close the last tab

### ISSUE THREAD

**Issue by WebShapedBiz** [alcinnz/Odysseus#55]
Hi.

When I close the last remaining tab the app does not close, leaving you without a way to create a new tab - entering a new URL does not create a new tab and the tab panel is gone so there is no "plus" button to create a new tab.
What's more, restarting the app does not solve this issue. So far the only way I see to continue using the Oddyseus is to open a new window from the menu, where tabs are working, and close the first one.

Cheers.

**Comment by alcinnz** [comment]
I actually had some code in there to fix this, but you're right: it isn't working. Trying a fix now.

**Comment by alcinnz** [comment]
In the existing code I had a test for whether how many tabs were still open. I tried the possibility that the count included the closing tab: it doesn't.

However in figuring that out it appears that a GTK method call wasn't doing what I expected. Now I'm making my second attempt to fix that code.

**Comment by alcinnz** [comment]
Fixed it! The problem was not in my check for how many tabs were left, but in my check for when I should just let the window close.

**Comment by ujon** [comment]
... perhaps you could add a Ctrl + Q to quit and save the state gracefully
