### ISSUE TITLE
Ctrl + L does not edit the current site link

### ISSUE THREAD

**Issue by zvirdaniel** [alcinnz/Odysseus#57]
In other browsers, Ctrl + L starts editing the current websites link. I do not know how to better explain this, just try it in a different browser.

**Comment by alcinnz** [comment]
I see what you mean. That Ctrl+L should focus the addressbar and select everything. 

Easy enough, a fix is coming soon.

**Comment by alcinnz** [comment]
Fix committed and tested. It will be live on the AppCenter in a day or so.
