### ISSUE TITLE
Pushing middle mouse button does not auto scroll

### ISSUE THREAD

**Issue by zvirdaniel** [alcinnz/Odysseus#58]
When I press middle mouse button in other browsers, it starts autoscrolling automatically. It had to be enabled separately in Firefox i think, but it is the default behaviour in Windows. It would be great to have the ability to use this in here as well.

**Comment by alcinnz** [comment]
Yes, you're right. This would be useful, especially for long webpages.

It won't be quite as trivial to implement as some of your other feature requests, but I'll get onto it today.

**Comment by alcinnz** [comment]
I've committed a fix to this, though it could certainly be made nicer. But the basics work very well and other developments will make for more noticable improvements to Odysseus. As such I'm closing this issue.

I'll send a release off to the AppCenter now, so you should see these improvements very soon.

**Comment by alcinnz** [comment]
Interesting note: this feature is also very self-contained: https://github.com/alcinnz/Odysseus/blob/master/src/Traits/decorate/AutoScroll.vala.

I'm definitely very happy to have created a place to put these self-contained pieces of functionality.
