### ISSUE TITLE
Can't translate it

### ISSUE THREAD

**Issue by zvirdaniel** [alcinnz/Odysseus#62]
I requested a new language here (https://www.transifex.com/none-483/odysseus/) - Czech language, but I got no response from the request. Given that you answered my issues here basically immidiately (glad for that!) I believe it might be a technical problem?

**Comment by alcinnz** [comment]
I had no technical issue and I received and activated your language request fine. The only issue was that a live in a relatively odd time zone, so I'll often (but not always) be sleeping while it's day for you.

**Comment by alcinnz** [comment]
It's all about timing.

**Comment by zvirdaniel** [comment]
Where are you? I live in the Czech republic, it's 18:51 right now.

**Comment by zvirdaniel** [comment]
I translated everything to czech

**Comment by alcinnz** [comment]
Great! I'm keen to see how well my i18n worked. 

You may be interested to know I do have [more messages](https://github.com/alcinnz/Odysseus/tree/master/data/page-l10n) which I haven't managed to import into Transifex. At the sametime most of those are error messages I've disabled because they were overriding GitHub's and other's. 

In a nutshell the custom syntax I'm using there involves everything between curly braces to have special meaning, and while I avoid it sometimes HTML sneaks in because I don't want to split up sentances.

**Comment by alcinnz** [comment]
I just went to import your translations, and when I went to incorporate your translations into the AppCenter metadata it occurred to me I didn't know what I'm doing. 

Do you have any guidance to give on how to apply Transifex translations to my metadata files?

**Comment by zvirdaniel** [comment]
I'll look into it those other translations later on. 

Sorry, but I basically have no exprience with developing elementaryOS applications.

**Comment by alcinnz** [comment]
It's all right. But at least all your translations will be in the install, so once the latest update gets to you Odysseus should be fully localized.

**Comment by zvirdaniel** [comment]
Glad to hear it! Can I ask, do you use latest version of WebKitGtk to render the pages? Or is it the 2 year old one, provided when Ubuntu 16.04 came out?

**Comment by alcinnz** [comment]
It's the latest, with it's multiprocessing model turned on. 

I knew elementary switched to Epiphany for a reason: it worked better with the modern web, and I don't want Odysseus to be a downgrade in that regard.

**Comment by zvirdaniel** [comment]
Exactly what I was hoping for. Having the newest WebKitGtk should be a priority, to keep the browsing secure and maintain maximal compatibility with newest web sites.

**Comment by alcinnz** [comment]
I figured out how to localize my display in AppCenter.

The rest of your translations so far will be released with my next release or after you translate that next batch I linked you to.

**Comment by zvirdaniel** [comment]
You mean this file? https://github.com/alcinnz/Odysseus/blob/master/data/page-l10n/cs
I suppose I am to change the contents from english to czech, is that it? If so, is the letter 't' supposed to be on the end of the second line?

**Comment by alcinnz** [comment]
Yes, that is the correct file. 

You should type the czech translations between `{% trans %}` and `{% endmsg %}`.

And no, that `t` shouldn't be there. I'll look into it.
