### ISSUE TITLE
PDFs, Videos, etc fail to load on the "Deep Web"

### ISSUE THREAD

**Issue by alcinnz** [alcinnz/Odysseus#66]
Odysseus, in line with elementary's [principle of modularity](https://elementary.io/docs/human-interface-guidelines#concision), uses third party apps and the FreeDesktop.org standards to open anything that's not a webpage. 

On the surface web this worked extremely well. However it totally breaks on any site with authentication cookies.

**Comment by alcinnz** [comment]
@elementary, @GNOME - can we all agree on a standard filepath for a cookies database applications should use when handling HTTP links?

When I implemented this feature, I was aware that I was stretching the capabilities of FreeDesktop.Org standards.

**Comment by giovannicaligaris** [comment]
Epiphany 3.18 does not have support for PDF, but if you install browser-plugin-evince from Zesty and onward, epiphany is able to open PDF files within the browser.

I tried to do the same with Odysseus but I had no success.

https://packages.ubuntu.com/bionic/browser-plugin-evince

**Comment by giovannicaligaris** [comment]
![screenshot from 2018-01-03 22 37 41](https://user-images.githubusercontent.com/26255347/34543008-c0010b78-f0d6-11e7-957a-888bf6d88e6d.png)

**Comment by alcinnz** [comment]
I'll look into the plugin, but I quite like how Odysseus handles it on the surface/nonauthenticated Web. There I handle PDFs very successfully by handing the URL over to Evince itself (or whatever other app is set to open PDFs). 

I like this as it avoids minimizes new UI for people to learn, and I'm tempted to keep it because it almost always works and it's got an easy workaround of downloading the documents instead. But then maybe I can do a better job communicating the workaround until the OS fully allows me my ideal UI.

**Comment by alcinnz** [comment]
I have considered downloading the pages into the temp folder for display, but by handing the URI directly to Audience (etc) the familiar UI and video can (and will) start playing instantly before the videos finished downloading. Evince has the same opportunity too, but it doesn't take it yet.

**Comment by alcinnz** [comment]
@giovannicaligaris I looked into browser-plugin-evince. And I'm glad I did as it's certainly a great fallback for if I fail to get traction amongst the desktop developers (aside: it may be good to go beyond those for elementary OS, so @KDE) that it's a good idea for applications to be able to stream their files off the Web.

We're most the way there already, and doing so brings great advantages both to browsers like mine that are designed for any or all [Free Desktops](https://www.freedesktop.org/wiki/Specifications/) and the desktops we design for. It would help:

* Both of us to simplify our UI and source code (makes more of a difference to, say, Evince as they'd have less reason to split their efforts maintaining browser-plugin-evince).
* Aids us to migrate away from the instability of the NPAPI like other browsers are doing (this is a similar point to the last)
* Prevent one of us (or the user) from needing to install the browser plugins on the user's machine.
* Vastly increases how many file types can be handled smoothly.
* Gives more design flexibility in how different types documents are viewed. 
* And it helps move away some of the emphasis placed on browsers, thereby making things a bit more level.

**Comment by alcinnz** [comment]
I think I've almost got this solved! I've now got soup complaining about sharing a database from a whole bunch of subprocesses.

That'll be easy to solve, but I'll leave it until tomorrow.

**Comment by alcinnz** [comment]
Turned out not to be so trivial to solve.

The issue is LibSoup's CookieJarDB doesn't handle the psuedo-errors triggered by SQLite for concurrency (this isn't actually unusual databases, SQLite is just weaker at concurrency and hence triggers it more). I guess I could try switching my configuration to use a simpler cookie jar that should be able to handle concurrency better, before I resort to reimplementing Soup.CookieJarDB.

**Comment by giovannicaligaris** [comment]
Any progress on this?

**Comment by alcinnz** [comment]
I'm sorry, not yet. 

I've got an idea to try (whereby I switch to a flat file database for cookies, as when I try the technique with SQLite I keep on getting false errors), but that without extra effort that would lose your browser cookies. 

Or I guess I could download these files to the temp directory. On second thought I quite like that idea, I've got a nice downloads experience - so build on it. I'll do that.

**Comment by alcinnz** [comment]
Just committed a fix which simply has Odysseus handle the download. Sorry it took me so long.

Also I didn't bother with moving these downloads to the temp directory as it turned out that required some ugly code that really wouldn't bring much of a benefit over keeping the downloads folder nicely organized.

**Comment by alcinnz** [comment]
Still trying to release this fix. Currently the webservice for releasing new versions to AppCenter is erroring out, and as soon as that site is fixed I'll send this fix to you.
