### ISSUE TITLE
strange behaviour... or how to spawn never ending new-tabs

### ISSUE THREAD

**Issue by ghost** [alcinnz/Odysseus#70]
*please* read the whole issue before trying to replicate!

if a url with the characters `%5D` after the tld (i.e. `google.ca%5D`) is entered Odysseus begins  spawning never ending new tabs with the same address (i.e. `google.ca%5D`).  this is probably not the desired behaviour, altough im clueless as to why it happens or how to fix it!

the only fix i know of was to quit Odysseus and then remove the `com.github.alcinnz.odysseus` directory in `~/.config`, which is overkill.

make sure you back up said directory before attempting to replicate this bug or you *will* lose saved logins, open tabs, etc.

**Comment by alcinnz** [comment]
Hmmm, I don't fully know why it's happening, but I've got suspicions what's making it worse. Does this issue occur if you enter the URL into an existing tab or just new ones? I'll investigate it. 

P.S. You should be able to recover by just deleting `com.github.alcinnz.odysseus/UI.sqlite` or to be even more selective, open it in Sequeler from the AppCenter to delete just that tab.

**Comment by alcinnz** [comment]
Trying it in other browsers, this should probably either report an invalid URI or fallback to a search.

**Comment by glendo** [comment]
it seems to happen in any and all tabs!

**Comment by alcinnz** [comment]
I've tested it and found the same thing.

I can think of a couple techniques I could use to fix this:
* Throw in URL validation for manually entered URIs.
* Maybe it's needed to validate URIs when they're opened (I'll use [this link](https://google.ca%5D) to test if this is needed).

And judging the previous test, it probably won't help, but I could be more selective about when I apply lazy loading of webpages.

**Comment by alcinnz** [comment]
I think I see the core issue. When Odysseus fails to load a URL, it hands it off to another registered app on your computer.

However the problem here is probably that your URI triggers that code, which finds Odysseus to be the appropriate to open https URIs with thereby triggering the normal code for opening links from other apps (i.e. a new tab).

That'll be a simple fix.

**Comment by alcinnz** [comment]
That appeared to fix the issue, and I just committed it.

You want have this issue in the next release.
