### ISSUE TITLE
Why Webkit engine?

### ISSUE THREAD

**Issue by peteruithoven** [alcinnz/Odysseus#74]
Odysseus, just like [Epiphany / Gnome web](https://wiki.gnome.org/Apps/Web) uses [Webkit](https://en.wikipedia.org/wiki/WebKit) as engine, I'm curious as of why?  

At one time it was used by many popular browsers like Safari, Chrome / Chromium and Opera, but now it's those last two moved to the newer Blink engine:
> On April 3, 2013, Google announced that it had forked WebCore, a component of WebKit, to be used in future versions of Google Chrome and the Opera web browser, under the name Blink.

In the mean time Mozilla is working on [Servo](https://en.wikipedia.org/wiki/Servo_(layout_engine)), which is early days, but already partly merged into Firefox (Quantum). 
And:
> Servo intends to re-implement the Chromium Embedded Framework (CEF) API. This would allow Servo to be used as a drop-in replacement for Chromium in applications using CEF, and positions Servo as a competitor to Chromium in these cases.[22]

I'm assuming using Webkit is easier because of the [WebkitGTK](https://webkitgtk.org/) project? Is webkit the only engine with proper GTK3 bindings?

I got curious seeing multiple people complain about mayor issues with Youtube playback in both Odysseus and Gnome web, see: ([Seek broken on YouTube](https://bugs.webkit.org/show_bug.cgi?id=183085)). 

I'm curious if you're thinking about moving to another engine.

I'm asking here honestly because I hate Bugzilla, where Epiphany / Gnome web host their issues.
The project also doesn't seem to have been migrated to Gnome's new gitlab instance. 
I did find a new project: [eolie](https://gitlab.gnome.org/gnumdk/eolie), but this also uses WebKitGTK.

**Comment by alcinnz** [comment]
Yes, you're correct about WebKit being the one browser engine with GTK bindings and that's the dominant reason I'm using it. Furthermore it has better integrations into the GNOME system elementary is built upon (but not by much), and I like the fact I'm sharing an engine with other elementary apps like Mail.

As such while I'm open to switching to another engine, I have no plans to for the foreseeable future.

**Comment by peteruithoven** [comment]
Thanks for the answer.
