### ISSUE TITLE
About page/window

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#89]
Would it possible to add a About page or window with the version of Odysseus. That way is a bit easier to keep track of the browser version. 

Epiphany and Opera browser both have two simple pages/windows.

![screenshot from 2018-03-21 08 19 46](https://user-images.githubusercontent.com/26255347/37699792-e74b8ac8-2ce0-11e8-8dde-9cf72d36706f.png)

![screenshot from 2018-03-21 08 20 01](https://user-images.githubusercontent.com/26255347/37699794-ea7c0d8a-2ce0-11e8-8ef7-a37bc33249f7.png)

**Comment by alcinnz** [comment]
The simplest thing for me to do for this is to link to Odysseus's AppCenter page, as outside of that I haven't been keeping my metadata up to date very well. And besides that's [what elementary's encouraging](https://medium.com/elementaryos/peace-out-about-dialogs-8efa956c0562). 

I could add links there to my application launcher and/or my app menu. How does that sound?

**Comment by giovannicaligaris** [comment]
That sounds fine too

**Comment by alcinnz** [comment]
Committed now, and it works well.

In the end I put it in the app menu but not the launcher's menu. Thought there was little point to the latter and it'll only be clutter in the Slingshot search (as application actions do show up there).

---

You'll see this in the next release of Odysseus (version 1.2.3?), which'll probably come out in about a week or so. Until then I've got a list of periphery things to look into.
