### ISSUE TITLE
Completed Download popup is not helpful

### ISSUE THREAD

**Issue by tdannecy** [alcinnz/Odysseus#95]
The popup that appears when a download is completed displays the entire URL of the downloaded file. This is confusing and it disappears too quickly for me to read the entire thing.

It would be nice to display the filename instead of the source URL.

![screenshot](https://user-images.githubusercontent.com/5177612/38963272-0ce0ca68-433f-11e8-8499-a5575de334cf.png)

**Comment by alcinnz** [comment]
Thanks for the feedback, I'll add it in the next release.

Though I would think it'd be useful if I included the website's domain in the popover as well, but certainly nothing else.

**Comment by alcinnz** [comment]
I've just committed a fix I hope you like, and am currently preparing to release a new update. You should be able get it from the AppCenter within the next few days.
